services:
  app:
    entrypoint:
    - sleep
    - infinity
    build:
      context: G:\Coding Project Programming\Transcription
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock